### ISSUE TITLE
Visible property not working on all elements

### ISSUE THREAD

**Issue by diamondq** [ebernerd/Cobalt#3]
In a number of elements (such as Radio), there is an order of operations bug in the draw routine.

The code fragment
```
if self.state == cobalt.state or self.state == "_ALL" and self.visible then
```
should be
```
if (self.state == cobalt.state or self.state == "_ALL") and self.visible then
```
as the AND is only matching against the _ALL case. Once you start using state, the visible property is currently being ignored, and I don't think that's intended.

**Comment by ebernerd** [comment]
Thanks. I am not planning another major 1.x release, and Cobalt 2.0 will be a sort of rewrite / re... I dunno, fix of all the code. This will certainly be fixed then. :)
