### ISSUE TITLE
Certain number below/above percentage

### ISSUE THREAD

**Issue by LoganDark** [ebernerd/Cobalt#6]
Basically specifying values like `100% - 2` or `50% + 1`

**Comment by ebernerd** [comment]
This is quite difficult to do considering that percentages are calculated as strings. If you're going to need something like this, use the parent's width.

```lua

--You suggested:
local value = "50% - 2"

--It can be accomplished as:
local value = math.ceil(obj.parent.w * 0.5) - 2
```

**Comment by LoganDark** [comment]
It's not that difficult really, with `string.match` you can store the offset if it is found and then continue to treat the percentage the exact same, except adding the offset

**Comment by ebernerd** [comment]
My problem with this is if what if someone inputs something like this:
```lua
local value = "((25% - 2) * 3) - 1"
```
There's a lot to keep track of, including order of operations and multiple mathematical expressions.
I don't see any added benefit of having this system be extended past simple percentages when, if you need something more advanced, you type at most 13 extra characters. It becomes easier if you save it to a variable, like (pseudocode) `local quarterWindow = window.w * .25`

**Comment by LoganDark** [comment]
I didn't suggest supporting all math. `+ 1` or `- 1`, that is all. No need for complicated math expressions.

Who needs `((25% - 2)) * 3) - 1` anyway? It's the same as `75% - 7`

**Comment by ebernerd** [comment]
The point is not that that particular case is necessary, but it would be confusing for people who'd want to do something like that and cant for the reasons of "I made it so you could only add or subtract one number".

**Comment by LoganDark** [comment]
So? They would be using percentages incorrectly - their fault
